#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;36m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[36m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;36m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)

clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
clear
echo -e "\033[0;34m┌──────────────────────────────────────────┐\033[0m"
echo -e "  \033[1;96m            MENU ALL SERVICE            $NC"
echo -e "\033[0;34m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[0;34m┌──────────────────────────────────────────┐\033[0m"
echo -e "\033[0;34m ${NC}${GREEN} [01]•${NC} RUNNING SYSTEM${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [02]•${NC} PORT VPS INFO${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [03]•${NC} LOAD VPS INFO${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [04]•${NC} AUTOREBOOT SERVER${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [05]•${NC} RESTART SERVICE${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [06]•${NC} REBOOT SERVICE${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [07]•${NC} CLEAR CACHE${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [08]•${NC} CEK BANDWITH${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [09]•${NC} AUTOKILL${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [10]•${NC} AUTO REBOOT${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [11]•${NC} INSTALL PLUGIN BOT SELLER${NC}"
echo -e "\033[0;34m ${NC}${GREEN} [12]•${NC} GANTI VERSI DROPBEAR${NC}"
echo -e "\033[0;34m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1 | 01)
    run
    ;;
2 | 02)
    prot
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
    ;;
3 | 03)
    clear
gotop
echo ""
echo -e " ${GREEN} Back to menu in 1 sec ${NC}"
sleep 1
menu
    ;;
4 | 04)
    autoreboot
    ;;
5 | 05)
    restart
    ;;
6 | 06)
    reboot
    ;;   
 7 | 07)
    clearcache
    ;;
8 | 08)
   bw
   ;;
9 | 09)
  autokill
  ;;
10)
  autoreboot
  ;;
11)
  install-plugin
  ;;
12)
  ganti-versi-db
  ;;
*)
   menu
  ;;
esac
