#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;36m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[36m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;36m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
clear
echo -e "\033[0;34m┌──────────────────────────────────────────┐\033[0m"
echo -e "                 MENU VLESS              $NC"
echo -e "\033[0;34m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[0;34m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${GREEN}1.${NC} ${WHITE}Create Account XRAY Vless WS/GRPC${NC}"
echo -e "  ${GREEN}2.${NC} ${WHITE}Create Trial XRAY Vless WS/GRPC${NC}"
echo -e "  ${GREEN}3.${NC} ${WHITE}Delete Account XRAY Vless WS/GRPC${NC}"
echo -e "  ${GREEN}4.${NC} ${WHITE}Renew Vless Account${NC}"
echo -e "  ${GREEN}5.${NC} ${WHITE}Check Vless login Account${NC}"
echo -e "  ${GREEN}6.${NC} ${WHITE}Check Config Vless Account${NC}"
echo -e "\033[0;34m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)  clear ;
    addvless
    ;;
2) clear ;
    trialvless
    ;;
3) clear ;
    delvless
    ;;
4) clear ;
    renewvless
    ;;
5) clear ;
    cekvless
    ;;
6) clear ;
    user-vless
    ;;
*)
    menu
    ;;
esac
