#!/bin/bash
# My Telegram : https://t.me/MRZST0RE
# ==========================================
# Color
GREEN='\e[36m'
RED='\033[0;31m'
BGBLUE='\e[1;44m'
ORANGE='\033[0;33m'
BLUE='\033[1;36m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BG='\E[44;1;39m'
NC='\033[0;37m'
WHITE='\033[0;37m'
r="\033[1;31m"  #REDTERANG
# ==========================================
# Getting
MYIP=$(wget -qO- ipinfo.io/ip);
clear
echo -e "$BLUE┌──────────────────────────────────────────┐$NC"
echo "   USERNAME       EXP DATE         STATUS"
echo -e "$BLUE└──────────────────────────────────────────┘$NC"
echo -e "$BLUE┌──────────────────────────────────────────┐$NC"
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "LOCKED${NORMAL}"
else
 printf "%-17s %2s %-17s %2s \n" "  $AKUN" "$exp   " "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "$BLUE└──────────────────────────────────────────┘$NC"
echo -e "$BLUE┌──────────────────────────────────────────┐$NC"
echo "   Account number: $JUMLAH   user"
echo -e "$BLUE└──────────────────────────────────────────┘$NC"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws