#!/bin/bash
# My Telegram : https://t.me/BangToyibbz
# ==========================================
# Color
GREEN='\e[36m'
RED='\033[0;31m'
BGBLUE='\e[1;44m'
ORANGE='\033[0;33m'
BLUE='\033[1;36m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
BG='\E[44;1;39m'
NC='\033[0;37m'
WHITE='\033[0;37m'
r="\033[1;31m"  #REDTERANG
# ==========================================
clear
echo -e ""
echo -e " ${GREEN} Starting Restart All Service ${NC}"
sleep 2
systemctl restart ws
systemctl restart haproxy
systemctl restart xray
systemctl restart openvpn
/etc/init.d/ssh restart
systemctl restart ssh
/etc/init.d/dropbear restart
/etc/init.d/openvpn restart
/etc/init.d/fail2ban restart
/etc/init.d/nginx restart
systemctl restart udp-mini-1
systemctl restart udp-mini-2
systemctl restart udp-mini-3
echo ""
echo -e " ${GREEN} Back to menu in 2 sec ${NC}"
sleep 2
menu