#!/bin/bash
clear
RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;36m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'
clear
figlet "Restore" | lolcat
echo "This Feature Can Only Be Used According To Vps Data With This Autoscript"
echo "Please input link to your vps data backup file."
echo "You can check it on your email if you run backup data vps before."
read -rp "Link File: " -e url
wget -O backup.zip "$url"
unzip backup.zip
rm -f backup.zip
sleep 1
cd /root/backup
cp passwd /etc/
cp group /etc/
cp shadow /etc/
cp gshadow /etc/
cp -r xray /etc/
cp -r html /var/www/
cp crontab /etc/
cp .ssh.db /etc/ssh/
cp .vmess.db /etc/vmess/
cp .vless.db /etc/vless/
cp .trojan.db /etc/trojan/
cp .shadowsocks.db /etc/shadowsocks/
cp -r kyt2/. /var/lib/
cp -r limit /etc/
cp -r kyt-limit/. /etc/kyt/limit/
cp -r vmess /etc/
cp -r trojan /etc/
cp -r vless /etc/
cp -r shadowsocks /etc/
rm -rf /root/backup
rm -f backup.zip
echo "Restore Berhasil!!!" | lolcat
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu